-- 사용자 잔고 테이블
CREATE TABLE `USER_MONEY` (
  `USER_ID` int(11) NOT NULL,
  `MONEY` bigint(20) NOT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 뿌리기 마스터 테이블
CREATE TABLE `DIVVYUP_MASTER` (
  `TOKEN` varchar(3) NOT NULL,
  `ROOM_ID` varchar(50) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  `MONEY` bigint(20) NOT NULL,
  `COUNT` int(11) NOT NULL,
  `INSERT_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ROOM_ID`,`TOKEN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 뿌리기 세부 목록 테이블
CREATE TABLE `DIVVYUP_TAKE_LIST` (
  `SEQNO` int(11) NOT NULL AUTO_INCREMENT,
  `TOKEN` varchar(3) NOT NULL,
  `ROOM_ID` varchar(50) NOT NULL,
  `TAKE_MONEY` bigint(20) NOT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  `TAKE_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`SEQNO`),
  KEY `DIVVYUP_TAKE_LIST_TOKEN_IDX` (`TOKEN`,`ROOM_ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1219 DEFAULT CHARSET=utf8mb4